Check readmetxt present
WordPress/plugin-check-legacy pull request #42
Opened 2023-06-14 22:17 UTC by EvanHerman

I reviewed a plugin that just didn't have a `readme.txt` file.

This checks that a `readme.txt` file exists before continuing to the other checks.

2023-06-20 05:16 UTC, dd32 approved these changes

2023-08-29 20:04 UTC, bordoni requested changes

2023-08-29 20:04 UTC, bordoni commented on checks/readme.php
> +		}
Invert the conditional and bail to reduce cognitive load for long-term maintenance.
Also translations.
```suggestion
		if ( $this->readme ) {
			return;
		}
		return new Error(
			'readme_missing',
			__( 'No readme.txt or readme.md was not found. readme.txt/readme.md is a required file.', 'wporg-plugins' )
		);
```

2023-09-01 15:39 UTC, bordoni approved these changes

2023-09-01 16:31 UTC, bordoni approved these changes

2023-09-01 21:03 UTC, merged