Add a check for ALLOW_UNFILTERED_UPLOADS
WordPress/plugin-check-legacy pull request #45
Opened 2023-06-15 11:20 UTC by EvanHerman

Resolves #8 

Check for the existence of `ALLOW_UNFILTERED_UPLOADS` in the codebase.

2023-06-20 02:27 UTC, dd32 approved these changes
LGTM.

I would have thought this would be covered by the `WordPress.WP.DiscouragedConstants` PHPCS check, but evidently not:

https://github.com/WordPress/WordPress-Coding-Standards/blob/cb90f0181b420776c3fa0ea1925f6746b5d1823f/WordPress/Sniffs/WP/DiscouragedConstantsSniff.php#L28

2023-08-29 19:56 UTC, bordoni requested changes
Small changes.

2023-08-29 19:56 UTC, bordoni commented on checks/check-constants.php
> +	function check_allow_unfiltered_uploads() {
```suggestion
	public function check_allow_unfiltered_uploads() {
```

2023-08-29 19:56 UTC, bordoni commented on checks/check-constants.php
> +		}
Invert the conditional and bail to reduce cognitive load for long-term maintenance.

```suggestion
		if ( ! $this->scan_matching_files_for_needle( 'ALLOW_UNFILTERED_UPLOADS', '\.php$' ) ) {
			return;
		}

		return new Error(
			'allow_unfiltered_uploads_detected',
			__( 'ALLOW_UNFILTERED_UPLOADS is not permitted.', 'wporg-plugins' )
		);
```

2023-09-01 15:40 UTC, bordoni approved these changes

2023-09-01 20:56 UTC, merged